### PR TITLE
samples: bluetooth: Remove CONFIG_BT_DEBUG_LOG use

### PR DESCRIPTION
**Pull request by rlubos**
CONFIG_BT_DEBUG_LOG no longer exists, a hidden symbol CONFIG_BT_LOG should be enabled instead, hence make sure the dependencies for the symbol are satisfied (CONFIG_BT && CONFIG_LOG).

### CODE REVIEW

**Review by kapi-no — APPROVED** [review]
Minor improvement: samples that do enable `CONFIG_NCS_SAMPLES_DEFAULTS` do not need to enable `CONFIG_LOG` in their `prj.conf`:

```
config NCS_SAMPLES_DEFAULTS
	bool "Enable NCS sample default settings"
	default n
	imply LOG
```

**Comment by rlubos** [comment]
> Minor improvement: samples that do enable `CONFIG_NCS_SAMPLES_DEFAULTS` do not need to enable `CONFIG_LOG` in their `prj.conf`:
> 
> ```
> config NCS_SAMPLES_DEFAULTS
> 	bool "Enable NCS sample default settings"
> 	default n
> 	imply LOG
> ```

Ok, I've followed the suggestion and removed it from samples that enable NCS defaults.

**Review by miha-nordic — APPROVED** [review]

**Comment by rlubos** [comment]
CC @bjarki-andreasen

**Comment by bjarki-andreasen** [comment]
cherry-picked

**Pull request closed without merging**
